# This is a basic workflow to help you get started with Actions

name: BUILD_WORKFLOW

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, aarush-dev ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14

    - name: install dependencies
      run: npm install
     
    - name: set github secrets build windows
      env:
        GH_TOKEN: ${{secrets.PERSON_TOKEN}}
      run: npm run buildwin
    - name: remove from dist
      run: npm run createfolder
    - uses: shallwefootball/s3-upload-action@master
      name: Upload to S3
      id: S3
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET_NAME }}
        source_dir: 'dist'
        destination_dir: windows

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: set github secrets build macos
      env:
        GH_TOKEN: ${{secrets.PERSON_TOKEN}}
      run: npm run buildmac
    - name: remove from dist
      run: npm run macDeleteFiles
    - uses: shallwefootball/s3-upload-action@master
      name: Upload to S3
      id: S3
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET_NAME }}
        source_dir: 'dist'
        destination_dir: macos

  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14

    - name: install dependencies
      run: npm install
     
    - name: set github secrets build windows
      env:
        GH_TOKEN: ${{secrets.PERSON_TOKEN}}
      run: npm run buildLinux
    - name: remove from dist
      run: npm run linuxDeleteFiles    
    - uses: shallwefootball/s3-upload-action@master
      name: Upload to S3
      id: S3
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET_NAME }}
        source_dir: 'dist'
        destination_dir: linux